"use client"

import { useEffect, useState } from "react"
import { Activity, Bell, CalendarDays, CheckCircle2, ChevronDown, Clock3, Database, History, House, Menu, Radio, Server, Settings, ShieldCheck, Thermometer, TrendingDown, TrendingUp, UserRound } from "lucide-react"
import { Area, AreaChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"

type Reading = { time: string; temperature: number }
const seedEndTime = Date.UTC(2025, 4, 10, 7, 32)
const seed: Reading[] = Array.from({ length: 61 }, (_, i) => ({ time: new Date(seedEndTime - (60-i)*60000).toISOString(), temperature: +(25.65 + Math.sin(i/4)*.36 + Math.sin(i/1.8)*.14 + i*.008).toFixed(1) }))
const nav = [["Dashboard",House],["Grafik",Activity],["Riwayat",History],["Peringatan",Bell],["Pengaturan",Settings]] as const
const clock = (v:string, seconds=false) => new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Bangkok",hour:"2-digit",minute:"2-digit",second:seconds?"2-digit":undefined}).format(new Date(v))

function Sidebar(){return <div className="flex h-full flex-col bg-white p-4"><div className="mb-10 grid size-12 place-items-center rounded-2xl bg-emerald-600 text-white shadow-lg shadow-emerald-200"><Server/></div><nav className="space-y-2">{nav.map(([label,Icon],i)=><Button key={label} variant="ghost" className={`w-full justify-start gap-3 ${i===0?"bg-emerald-50 text-emerald-700":"text-slate-500"}`}><Icon className="size-5"/>{label}{label==="Peringatan"&&<Badge className="ml-auto rounded-full bg-emerald-600">2</Badge>}</Button>)}</nav><div className="mt-auto flex gap-2 px-3 text-xs text-slate-400"><Radio className="size-4 text-emerald-600"/>ESP32 Monitor</div></div>}
function Metric({icon:Icon,label,value,detail}:{icon:typeof Thermometer,label:string,value:string,detail:string}){return <Card className="border-slate-200/80 shadow-sm"><CardContent className="flex min-h-32 items-center gap-4 p-5"><div className="grid size-14 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Icon className="size-7"/></div><div className="min-w-0"><p className="text-sm text-slate-500">{label}</p><p className="truncate text-2xl font-semibold text-emerald-600">{value}</p><p className="text-sm text-slate-500">{detail}</p></div></CardContent></Card>}
function Limit({color,label,value}:{color:string,label:string,value:string}){return <div className="flex items-center rounded-xl border px-3 py-3 text-sm"><span className={`mr-3 size-2 rounded-full ${color}`}/><span>{label}</span><b className="ml-auto font-medium">{value}</b></div>}

export function Dashboard(){
 const [period,setPeriod]=useState("1"),[data,setData]=useState(seed)
 useEffect(()=>{const timer=setInterval(()=>setData(old=>{const prev=old.at(-1)?.temperature??26;const next=Math.max(24.8,Math.min(29.4,prev+(Math.random()-.48)*.22));return [...old.slice(1),{time:new Date().toISOString(),temperature:+next.toFixed(1)}]}),4000);return()=>clearInterval(timer)},[])
 const current=data.at(-1)!,recent=[...data].reverse().slice(0,5)
 return <div className="min-h-screen p-2 lg:flex"><aside className="sticky top-2 hidden h-[calc(100vh-1rem)] w-56 shrink-0 overflow-hidden rounded-3xl border bg-white shadow-sm lg:block"><Sidebar/></aside><main className="min-w-0 flex-1 px-2 pb-6 lg:px-6">
 <header className="flex min-h-20 items-center gap-3"><Sheet><SheetTrigger asChild><Button size="icon" variant="outline" className="lg:hidden"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-64 p-0"><SheetTitle className="sr-only">Navigasi</SheetTitle><Sidebar/></SheetContent></Sheet><h1 className="text-xl font-semibold sm:text-2xl">Server Room Monitoring</h1><div className="ml-auto flex items-center gap-2"><span className="hidden items-center gap-2 text-sm text-slate-500 xl:flex"><CalendarDays className="size-4"/>10 Mei 2025, {clock(current.time)} WIB</span><Button variant="outline" className="border-red-100 bg-red-50 text-red-500"><Bell/><span className="hidden sm:inline">2 Peringatan</span></Button><Button size="icon" variant="outline"><UserRound/></Button><ChevronDown className="hidden size-4 sm:block"/></div></header>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Thermometer} label="Suhu Saat Ini" value={`${current.temperature.toFixed(1)}°C`} detail="Normal"/><Metric icon={ShieldCheck} label="Status Ruangan" value="Normal" detail="Kondisi aman"/><Metric icon={Radio} label="Sensor" value="Online" detail="Terhubung"/><Metric icon={Clock3} label="Update Terakhir" value={clock(current.time,true)} detail="10 Mei 2025"/></section>
 <section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><Card className="border-slate-200/80 shadow-sm"><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Grafik Suhu</CardTitle><p className="mt-3 text-xs text-slate-500">Suhu (°C)</p></div><Tabs value={period} onValueChange={setPeriod}><TabsList>{[1,6,24].map(x=><TabsTrigger key={x} value={`${x}`}>{x} Jam</TabsTrigger>)}</TabsList></Tabs></CardHeader><CardContent className="h-80 pl-1"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:20,right:20,left:-10}}><defs><linearGradient id="temp" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#10b981" stopOpacity={.22}/><stop offset="1" stopColor="#10b981" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf1ef"/><XAxis dataKey="time" tickFormatter={v=>clock(v)} axisLine={false} tickLine={false} minTickGap={45} fontSize={11}/><YAxis domain={[18,36]} ticks={[18,21,24,27,30,33,36]} axisLine={false} tickLine={false} fontSize={11}/><Tooltip labelFormatter={v=>clock(String(v),true)} formatter={v=>[`${Number(v).toFixed(1)}°C`,"Suhu"]}/><ReferenceLine y={30} stroke="#fb7185" strokeDasharray="5 4" label={{value:"Bahaya (≥30°C)",fill:"#f43f5e",fontSize:11,position:"insideTopLeft"}}/><ReferenceLine y={27} stroke="#f59e0b" strokeDasharray="5 4" label={{value:"Waspada (27–30°C)",fill:"#d97706",fontSize:11,position:"insideTopLeft"}}/><Area type="monotone" dataKey="temperature" stroke="#10b981" strokeWidth={2.4} fill="url(#temp)"/></AreaChart></ResponsiveContainer></CardContent></Card>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><Card><CardHeader><CardTitle>Batas Suhu</CardTitle></CardHeader><CardContent className="space-y-2"><Limit color="bg-emerald-500" label="Normal" value="≤ 27°C"/><Limit color="bg-amber-400" label="Waspada" value="27–30°C"/><Limit color="bg-rose-500" label="Bahaya" value="≥ 30°C"/></CardContent></Card><Card><CardHeader><CardTitle>Peringatan Terbaru</CardTitle></CardHeader><CardContent className="divide-y p-0">{[["Suhu mendekati batas waspada","29.1°C","14:18",false],["Suhu kembali normal","26.7°C","13:58",true],["Sistem mulai dimonitoring","Monitoring dimulai","13:32",true]].map(([title,detail,time,ok])=><div key={String(title)} className="flex items-center gap-3 px-5 py-3"><div className={`grid size-8 place-items-center rounded-full ${ok?"bg-emerald-50 text-emerald-600":"bg-amber-50 text-amber-500"}`}>{ok?<CheckCircle2 className="size-4"/>:<Bell className="size-4"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{title}</p><p className="text-xs text-slate-400">{detail}</p></div><time className="text-xs text-slate-400">{time}</time></div>)}</CardContent></Card></div></section>
 <section className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_1fr_.85fr]"><Card><CardHeader><CardTitle>Data Terakhir</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>Waktu</TableHead><TableHead>Suhu</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{recent.map(row=><TableRow key={row.time}><TableCell>{clock(row.time,true)}</TableCell><TableCell>{row.temperature.toFixed(1)}°C</TableCell><TableCell><Badge variant="secondary" className="bg-emerald-50 text-emerald-700">● Normal</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle>Ringkasan Hari Ini</CardTitle></CardHeader><CardContent className="divide-y"><SummaryRow icon={TrendingUp} label="Suhu Tertinggi" value="28.9°C" color="bg-rose-50 text-rose-500"/><SummaryRow icon={TrendingDown} label="Suhu Terendah" value="24.8°C" color="bg-blue-50 text-blue-500"/><SummaryRow icon={Activity} label="Rata-rata" value="26.2°C" color="bg-emerald-50 text-emerald-600"/></CardContent></Card><Card><CardHeader><CardTitle>Status Sistem</CardTitle></CardHeader><CardContent className="divide-y"><SystemRow icon={CheckCircle2} label="Aplikasi"/><SystemRow icon={Database} label="Database"/><SystemRow icon={Radio} label="Sensor"/></CardContent></Card></section>
 </main></div>
}

function SummaryRow({icon:Icon,label,value,color}:{icon:typeof Activity,label:string,value:string,color:string}){return <div className="flex items-center gap-4 py-3"><span className={`grid size-11 place-items-center rounded-full ${color}`}><Icon className="size-5"/></span><span><small className="text-slate-500">{label}</small><b className="block text-lg">{value}</b></span></div>}
function SystemRow({icon:Icon,label}:{icon:typeof Activity,label:string}){return <div className="flex items-center py-4 text-sm"><Icon className="mr-2 size-4 text-emerald-600"/>{label}<span className="ml-auto text-emerald-600">Online</span></div>}
